# Generated by Django 4.1.5 on 2023-01-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follower',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followings',
        ),
    ]
