# Generated by Django 4.1.5 on 2023-01-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_follower_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
