# Generated by Django 4.1.5 on 2023-01-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_likers_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
