# Generated by Django 4.1.5 on 2023-01-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_item',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_item',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.listing'),
        ),
    ]
