# Generated by Django 4.1.5 on 2023-01-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_bid_item_remove_comment_comment_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.listing'),
        ),
    ]
