# Generated by Django 4.1.6 on 2023-02-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_planned_planned_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planned',
            name='recurrence',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Anually')], null=True),
        ),
        migrations.AlterField(
            model_name='planned',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
