# Generated by Django 4.1.6 on 2023-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_planned_delete_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='planned',
            name='planned_type',
            field=models.PositiveIntegerField(choices=[(1, 'Income'), (2, 'Expense')], default=1),
            preserve_default=False,
        ),
    ]
