# Generated by Django 4.1.6 on 2023-02-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_planned_recurrence_alter_planned_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Food & Drinks'), (2, 'Shopping'), (3, 'Housing'), (4, 'Transportation'), (5, 'Vehicle'), (6, 'Life & Entertainment'), (7, 'Communication, Technology'), (8, 'Financial Expenses'), (9, 'Investments'), (10, 'Income'), (11, 'Others'), (0, 'Planned Payment')]),
        ),
    ]
